server {
    listen 80;
    listen [::]:80;
    server_name 192.168.1.161;

    location / {
        proxy_pass http://192.168.1.94:4010;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # # Add/extend the Via header on the upstream request
        # proxy_set_header Via $proxy_add_via;

        # Add a Via header on the response Nginx sends back to the client
        # Response
        # add_header Access-Control-Expose-Headers "X-Nginx-Naja" always;

        # add_header X-Ngix-naja "helloworld" always;

        proxy_http_version 1.1;

        proxy_read_timeout 60s;
        proxy_buffering off;
    }
}
